# File copied from https://github.com/FRBCesab/rcompendium/.github/workflows/update-citation-cff.yaml
# Workflow derived from https://github.com/r-lib/actions/tree/master/examples

on:
  release:
    types: [released, published]
    paths:
      - inst/CITATION
  workflow_dispatch:

name: Update CITATION.cff

jobs:
  update-citation-cff:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Update CITATION.cff
        run: |
          # Update CITATION.cff file
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "The latest published version is $latest_tag"
          awk -v ref="$latest_tag" '/^version:/ { print "version: " ref; next }1' CITATION.cff > CITATION.cff.tmp && mv CITATION.cff.tmp CITATION.cff

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add CITATION.cff
          git commit -m 'doc: update CITATION.cff' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
